### ISSUE TITLE
We need a method for capturing the screen shots of failed selenium tests

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap-extras#7]
We need a method for capturing the screen shots of failed selenium tests.  At the moment we can do this but the screen shot are captured by a private web site.  (See the 'after_failure' step at https://github.com/ctsit/redcap-extras/blob/master/.travis.yml#L22).  We should investigate the Sauce Labs integration with Travis-CI (see http://docs.travis-ci.com/user/sauce-connect/) to see if we can get this functionality by using Sauce Labs for the selenium tests.

**Comment by pbchase** [comment]
Closed by pull request #18.

**Comment by ufl-taeber** [comment]
It looks like the `after_failure` step wasn't changed with this pull request. I think we should remove it.

**Comment by pbchase** [comment]
Taeber, recheck the develop branch. I think you'll see the changes you want. https://github.com/ctsit/redcap-extras/blob/develop/.travis.yml

**Comment by ufl-taeber** [comment]
Yep, sorry. I was looking at the main branch. Thanks!

**Comment by pbchase** [comment]
NP.
